name: Lighthouse Reuse CI

on:
  workflow_dispatch:

env:
  API_URL: "https://market.axonivy.com/marketplace-service/api/product?type=all&language=en&isRESTClient=false"
  BASE_URL: "https://market.axonivy.com"
  BATCH_SIZE: 10
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    outputs:
      urls_batches: ${{ steps.process-urls.outputs.batches }}
    steps:
      - name: Fetch Product IDs in Batches
        run: |
          RESPONSE=$(curl -s "$API_URL&size=1000")
          TOTAL_PRODUCTS=$(echo "$RESPONSE" | jq -r '.page.totalElements')

          echo "Total Products: $TOTAL_PRODUCTS"

          # Clear the file before starting
          > urls_batches.txt
          for ((i=0; i<TOTAL_PRODUCTS; i+=$BATCH_SIZE)); do
            RESPONSE=$(curl -s "$API_URL&size=$BATCH_SIZE&page=$((i/$BATCH_SIZE))")
            BATCH_URLS=$(echo "$RESPONSE" | jq -r --arg base_url "$BASE_URL" '.["_embedded"]["products"][]["id"] | "\($base_url)/\(.)"' | paste -sd",")
            echo "$BATCH_URLS" >> urls_batches.txt
          done

      - name: Process URL Batches
        id: process-urls
        run: |
          URLs=$(cat urls_batches.txt | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "URLs: $URLs"
          echo "batches=${URLs}" >> "$GITHUB_OUTPUT"

  lighthouse:
    needs: fetch-urls
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Batch URLs: ${{ needs.fetch-urls.outputs.urls_batches }}"