name: Lighthouse CI
on:
    workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://market.axonivy.com
            https://market.axonivy.com/portal
          uploadArtifacts: true