name: Lighthouse Reuse CI

on:
  workflow_dispatch:

env:
  API_URL: "https://market.axonivy.com/marketplace-service/api/product?type=all&language=en&isRESTClient=false"
  BASE_URL: "https://market.axonivy.com"
  BATCH_SIZE: 10

jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    outputs:
      urls_batches: ${{ steps.set-env.outputs.urls_batches }}
    steps:
      - name: Fetch Product IDs in Batches
        id: set-env
        run: |
          RESPONSE=$(curl -s "$API_URL&size=1000")
          TOTAL_PRODUCTS=$(echo "$RESPONSE" | jq -r '.page.totalElements')

          echo "Total Products: $TOTAL_PRODUCTS"

          URL_BATCHES=""
          for ((i=0; i<TOTAL_PRODUCTS; i+=$BATCH_SIZE)); do
            RESPONSE=$(curl -s "$API_URL&size=$BATCH_SIZE&page=$((i/$BATCH_SIZE))")
            echo "$RESPONSE" | jq -r '.["_embedded"]["products"][]["id"]' | while read id; do
              URL="${BASE_URL}/${id}"
              URL_BATCHES+="${URL},"
            done
          done

          # Remove trailing comma
          URL_BATCHES=${URL_BATCHES%,}

          echo "urls_batches=$URL_BATCHES" >> $GITHUB_ENV
          echo "::set-output name=urls_batches::$URL_BATCHES"

  lighthouse:
    needs: fetch-urls
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: ${{ fromJson(needs.fetch-urls.outputs.urls_batches) }}
    steps:
      - run: |
          echo "Batch URLs: ${{ matrix.batch }}"